name: CI
on: [push, pull_request]
jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run linting
        run: bin/standardrb

  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.7, 3.1, 3.2, 3.3 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run specs
        run: bin/rspec
      - name: Run coverage report
        uses: coverallsapp/github-action@v2
        with:
          fail-on-error: false
