name: CI
on: [push, pull_request]
jobs:
  lint-and-test:
    name: Linting, specs and coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run linting
      run: bin/standardrb
    - name: Run specs
      run: bin/rspec
    - name: Run coverage report
      uses: coverallsapp/github-action@v2
      with:
        fail-on-error: false
