name: Unit tests
on: [push, pull_request]
jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.7, 3.1, 3.2, 3.3 ]
    runs-on: ubuntu-latest
    name: Run specs and coverage report
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run specs
        run: bin/rspec
      - name: Run coverage report
        uses: coverallsapp/github-action@v2
        with:
          fail-on-error: false
